In [1]:
import numpy as np
import numpy.linalg as la
from numpy.linalg import matrix_power as mpow
A = np.array([[2,1,-3],[-3,-6,1],[1,1,1]])
print("A:\n",A)
product=A@A
print("A^2:\n",product)
power=mpow(A,30)
print("A^30:\n",power)
det_A=la.det(A)
print("determinant of A:",det_A)
inv_A=la.inv(A)
print("inverse of A:",det_A)
rank=np.linalg.matrix_rank(A)
print("rank of matrix A:",rank)
trace=np.trace(A)
print("trace:",trace)

A:
 [[ 2  1 -3]
 [-3 -6  1]
 [ 1  1  1]]
A^2:
 [[-2 -7 -8]
 [13 34  4]
 [ 0 -4 -1]]
A^30:
 [[ 3085860415688368638 -5574303003843542351 -3164865871185752716]
 [-5301833918751420539 -7381572879268411534 -7572083603697442240]
 [ -137710995128914420  7296661613439613400  1364978258675151103]]
determinant of A: -19.000000000000004
inverse of A: -19.000000000000004
rank of matrix A: 3
trace: -3
