In [ ]:
import numpy as np
A=np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[7,8,9,10,11]])
print("A : \n",A)
rank=np.linalg.matrix_rank(A)
print("rank of matrix A is : ",rank)

A : 
 [[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 7  8  9 10 11]]
rank of matrix A is :  2


In [ ]:
import numpy as np
B=np.array([[3,4,5,6,7],[4,5,6,7,8],[5,6,7,8,9],[6,7,8,9,10]])
print("B : \n",B)
rank=np.linalg.matrix_rank(B)
print("rank of matrix B is : ",rank)

B : 
 [[ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]
rank of matrix B is :  2


In [ ]:
import numpy as np
C=np.array([[0,1,3,1],[1,0,1,1],[-3,1,0,-2],[-1,1,2,0]])
print("C : \n",C)
rank=np.linalg.matrix_rank(C)
print("rank of matrix C is : ",rank)

C : 
 [[ 0  1  3  1]
 [ 1  0  1  1]
 [-3  1  0 -2]
 [-1  1  2  0]]
rank of matrix C is :  2


In [ ]:
import numpy as np
D=np.array([[1,2,3],[2,3,1],[3,1,2]])
print("D : \n",D)
rank=np.linalg.matrix_rank(D)
print("rank of matrix D is : ",rank)

D : 
 [[1 2 3]
 [2 3 1]
 [3 1 2]]
rank of matrix D is :  3


In [ ]:
import numpy as np
E=np.array([[1,2,-1,2],[2,2,-1,1],[-1,-1,1,-1],[2,1,-1,2]])
print("E : \n",E)
rank=np.linalg.matrix_rank(E)
print("rank of matrix E is : ",rank)

E : 
 [[ 1  2 -1  2]
 [ 2  2 -1  1]
 [-1 -1  1 -1]
 [ 2  1 -1  2]]
rank of matrix E is :  4
