In [25]:
import numpy as np
import numpy.linalg as la
from numpy.linalg import matrix_power as mpow
import scipy.linalg as la
A = np.array([[2,-1,1],[-1,2,-1],[1,-1,2]])
print("A:\n",A)
rank=np.linalg.matrix_rank(A)
print("rank of matrix A is : ",rank)
trace=np.trace(A)
print("trace:",trace)
det_A=la.det(A)
print("determinant of A:",det_A)
inv_A=la.inv(A)
print("inverse of A:",det_A)
square=A@A
print("A^2:\n",square)
cube=A@A@A
print("A^3:\n",cube)
S1=np.trace(A)
print("S1 : Sum of diagonal element :",S1)
S2=la.det(A)
print("S2 : Sum of minor of diagonal elements :",S2)
I=np.eye(3)
print("I:\n",I)
CHT=cube-(S1*square)+(S2*A)-(det_A*I)
print("CHT : \n",CHT)
eig_val, eig_vec = la.eig(A)
print("Eigen value of A is : ",eig_val)
print("Eigen vector of A is : \n",eig_vec)

A:
 [[ 2 -1  1]
 [-1  2 -1]
 [ 1 -1  2]]
rank of matrix A is :  3
trace: 6
determinant of A: 4.0
inverse of A: 4.0
A^2:
 [[ 6 -5  5]
 [-5  6 -5]
 [ 5 -5  6]]
A^3:
 [[ 22 -21  21]
 [-21  22 -21]
 [ 21 -21  22]]
S1 : Sum of diagonal element : 6
S2 : Sum of minor of diagonal elements : 4.0
I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
CHT : 
 [[-10.   5.  -5.]
 [  5. -10.   5.]
 [ -5.   5. -10.]]
Eigen value of A is :  [1.+0.j 4.+0.j 1.+0.j]
Eigen vector of A is : 
 [[-0.81649658 -0.57735027 -0.32444284]
 [-0.40824829  0.57735027  0.48666426]
 [ 0.40824829 -0.57735027  0.81110711]]
