In [ ]:
import numpy as np
A = np.array([[2,1,-3],[-3,-6,1],[1,1,1]])
B=A@A
print("A=",A)
print("Square of matrix A is:")
print("A^2=",B)
C=A@A@A
print("Cube of matrix A is:")
print("A^3=",C)
D=A@A@A@A@A
print("Fifth power of matrix A is:")
print("A^5=",D)
E=A@A@A@A@A@A@A@A@A@A
print("Tenth power of matrix A is:")
print("A^10=",E)


A= [[ 2  1 -3]
 [-3 -6  1]
 [ 1  1  1]]
Square of matrix A is:
A^2= [[-2 -7 -8]
 [13 34  4]
 [ 0 -4 -1]]
Cube of matrix A is:
A^3= [[   9   32   -9]
 [ -72 -187   -1]
 [  11   23   -5]]
Fifth power of matrix A is:
A^5= [[  398  1061    65]
 [-2287 -5850  -171]
 [  277   725     9]]
Tenth power of matrix A is:
A^10= [[-2250098 -5737447  -154976]
 [12421357 31672018   850156]
 [-1545336 -3940828  -105889]]


In [ ]:
import numpy as np
A = np.array([[2,1,-3],[-3,-6,1],[1,1,1]])
print("A=",A)
B = np.array([[1,2,3],[2,3,1],[3,1,2]])
print("B=",B)
C=A@B
print("Product of matrix A and B is:")
print("AB=",C)
D=B@A
print("Product of matrix B and A is:")
print("BA=",D)


A= [[ 2  1 -3]
 [-3 -6  1]
 [ 1  1  1]]
B= [[1 2 3]
 [2 3 1]
 [3 1 2]]
Product of matrix A and B is:
AB= [[ -5   4   1]
 [-12 -23 -13]
 [  6   6   6]]
Product of matrix B and A is:
BA= [[ -1  -8   2]
 [ -4 -15  -2]
 [  5  -1  -6]]


In [ ]:
import numpy as np
import numpy.linalg as la
A = np.array([[2,1,-3],[-3,-6,1],[1,1,1]])
print("A=",A)
det_A = la.det(A)
print("determinant of A =",det_A)

A= [[ 2  1 -3]
 [-3 -6  1]
 [ 1  1  1]]
determinant of A = -19.000000000000004


In [ ]:
import numpy as np
import numpy.linalg as la
B = np.array([[2,1,-3,6,-2],[-3,-6,1,8,1],[1,1,1,1,1],[5,-2,-1,6,8],[1,1,1,1,1]])
print("B=",B)
det_B = la.det(B)
print("determinant of B =",det_B)

B= [[ 2  1 -3  6 -2]
 [-3 -6  1  8  1]
 [ 1  1  1  1  1]
 [ 5 -2 -1  6  8]
 [ 1  1  1  1  1]]
determinant of B = 0.0


In [ ]:
import numpy as np
import numpy.linalg as la
B = np.array([[10,2,-3,6,-2],[10,2,1,8,1],[10,2,5,6,1],[10,2,-1,6,8],[10,2,1,1,1]])
print("B=",B)
det_B = la.det(B)
print("determinant of B =",det_B)

B= [[10  2 -3  6 -2]
 [10  2  1  8  1]
 [10  2  5  6  1]
 [10  2 -1  6  8]
 [10  2  1  1  1]]
determinant of B = 0.0


In [ ]:
import numpy as np
import numpy.linalg as la
A = np.array([[2,1,-3],[-3,-6,1],[1,1,1]])
print("A=",A)
det_A = la.det(A)
print("determinant of A =",det_A)
inv_A = la.inv(A)
print("inverse of A =",inv_A)

A= [[ 2  1 -3]
 [-3 -6  1]
 [ 1  1  1]]
determinant of A = -19.000000000000004
inverse of A = [[ 0.36842105  0.21052632  0.89473684]
 [-0.21052632 -0.26315789 -0.36842105]
 [-0.15789474  0.05263158  0.47368421]]


In [ ]:
import numpy as np
import numpy.linalg as la
A = np.array([[5,7,-3],[2,0,1],[1,1,7]])
print("A=",A)
det_A = la.det(A)
print("determinant of A =",det_A)
inv_A = la.inv(A)
print("inverse of A =",inv_A)

A= [[ 5  7 -3]
 [ 2  0  1]
 [ 1  1  7]]
determinant of A = -102.00000000000004
inverse of A = [[ 0.00980392  0.50980392 -0.06862745]
 [ 0.12745098 -0.37254902  0.10784314]
 [-0.01960784 -0.01960784  0.1372549 ]]


In [ ]:
import numpy as np
import numpy.linalg as la
B = np.array([[10,2,-3,6,-2],[10,2,1,8,1],[10,2,5,6,1],[10,2,-1,6,8],[10,2,1,1,1]])
print("B=",B)
det_B = la.det(B)
print("determinant of B =",det_B)
inv_B = la.inv(B)
print("inverse of B =",inv_B)

B= [[10  2 -3  6 -2]
 [10  2  1  8  1]
 [10  2  5  6  1]
 [10  2 -1  6  8]
 [10  2  1  1  1]]
determinant of B = 0.0


LinAlgError: ignored

In [1]:
import numpy as np
import numpy.linalg as la
A=np.array([[-3,-3,-2],[23,2,1],[4,1,7]])
print("A=\n",A)
det_A=la.det(A)
print("\ndeterminat of A =\n",det_A)
inv_A=la.inv(A)
print("\nINVERSE OF MATRIX A IS:")
print("A^-1\n",inv_A)

A=
 [[-3 -3 -2]
 [23  2  1]
 [ 4  1  7]]

determinat of A =
 402.0

INVERSE OF MATRIX A IS:
A^-1
 [[ 0.03233831  0.04726368  0.00248756]
 [-0.39054726 -0.03233831 -0.10696517]
 [ 0.03731343 -0.02238806  0.15671642]]


In [2]:
import numpy as np
from numpy.linalg import matrix_power as mpow
A=np.array([[1,2,3],[3,3,4],[4,5,6]])
print("The given matrix:")
print("A=\n",A)
B=mpow(A,2)
print("Second power of A:")
print("A^2= \n",B)
C=mpow(A,3)
print("Third power of A:")
print("A^3= \n",C)
D=mpow(A,4)
print("Fourth power of A:")
print("A^4=\n",D)
X=mpow(A,25)
print("Twentyfifth power of A:")
print("A^25=\n",X)
M=mpow(A,100)
print("Hundredth power of A:")
print("A^100=\n",M)
N=mpow(A,500)
print("Five hundredth power of A:")
print("A^500=\n",N)
K=mpow(A,100000)
print("One lakh power of A:")
print("A^100000=\n",K)

The given matrix:
A=
 [[1 2 3]
 [3 3 4]
 [4 5 6]]
Second power of A:
A^2= 
 [[19 23 29]
 [28 35 45]
 [43 53 68]]
Third power of A:
A^3= 
 [[204 252 323]
 [313 386 494]
 [474 585 749]]
Fourth power of A:
A^4=
 [[2252 2779 3558]
 [3447 4254 5447]
 [5225 6448 8256]]
Twentyfifth power of A:
A^25=
 [[-1869526833953146220  -618460153380449443 -2074099447944972586]
 [ 1071415980388709813  1083876937292629514  1908595121572783513]
 [ 8199625978240148311 -5838075029659104428  4874459849722478948]]
Hundredth power of A:
A^100=
 [[  -45956115134374389   395571264744755415  5939859349996236917]
 [-6503863166723599932  5477277901119281163  6794164086479225597]
 [  353463126749103515   332409057751277565  5851795096866210628]]
Five hundredth power of A:
A^500=
 [[ -616259064056434800 -9088094279616402432 -4693778370379164711]
 [-6422574920318094289 -3359185119535792662 -1458241035462182826]
 [-4915834135340041982  6393667973652914051 -1137777290159239061]]
One lakh power of A:
A^100000=
 [[ 20607035

In [3]:
import numpy as np
import numpy.linalg as la
A=np.array([[1,2,3],[-2,4,5],[3,-9,5]])
print("A=\n",A) 
#np.trace(A)   
print("Trace of matrix A is:")  
print("Trace=",np.trace(A))   
det_A=la.det(A)
print("Determinant of A is:")
print("Determinant=",det_A)                                      

A=
 [[ 1  2  3]
 [-2  4  5]
 [ 3 -9  5]]
Trace of matrix A is:
Trace= 10
Determinant of A is:
Determinant= 133.0
