In [1]:
from numpy import*
A22=array([[1,2],[3,4]])
display (A22)
D22=linalg.det(A22)
display(A22,D22)
display(int(D22))

array([[1, 2],
       [3, 4]])

array([[1, 2],
       [3, 4]])

-2.0000000000000004

-2

In [2]:
from numpy import*
A33=array([[1,2,3],[4,5,6],[7,8,9]])
display (A22)
D33=linalg.det(A22)
display(A22,D22)
display(int(D33))

array([[1, 2],
       [3, 4]])

array([[1, 2],
       [3, 4]])

-2.0000000000000004

-2

In [8]:
print ('Jacobian of fi multivariable functions w.r.t. xj independent variables')
from sympy import *
V=symbols ('x,y,z')
x,y,z=symbols('x,y,z')
f=sympify(['x*y*z','x**2+y**2+z**2','x+y+z'])
NM=zeros(len(f),len(V))
print('\n Null matrix of order 3*3')
display(NM)
for i,fi in enumerate (f):
  for j,Vj in enumerate (V):
    NM[i,j]=diff(fi,Vj)
print('\n Matrix corresponding to Jacobian')
display (NM)
print ('\n Jacobian as function of x,y,z')
J= Matrix.det(NM)
display (simplify(J))
print('\n Jacobian at (x=1,y=2,z=3)')
#VJ=J.subs([(x,1),(y,2),(z,3)])
#display (VJ)


Jacobian of fi multivariable functions w.r.t. xj independent variables

 Null matrix of order 3*3


Matrix([
[0, 0, 0],
[0, 0, 0],
[0, 0, 0]])


 Matrix corresponding to Jacobian


Matrix([
[y*z, x*z, x*y],
[2*x, 2*y, 2*z],
[  1,   1,   1]])


 Jacobian as function of x,y,z


2*x**2*y - 2*x**2*z - 2*x*y**2 + 2*x*z**2 + 2*y**2*z - 2*y*z**2


 Jacobian at (x=1,y=2,z=3)


In [ ]:
print('\u03B8')

θ


In [3]:
from sympy import*
print(sin('\u03B8'))

sin(θ)


In [4]:
print('Jacobian of fi multivariable functions w.r.t xj independent variables')

Jacobian of fi multivariable functions w.r.t xj independent variables


In [5]:
print('Jacobian of fi multivariable functions w.r.t xj independent variables')
from sympy import*
a=symbols('x,y,z')
f=sympify(['x*y*z','x**2+y**2+z**2','x+y+z'])
nm=zeros(len(f),len(a))
print('\n null matrix of order 3*3')
display(nm)

Jacobian of fi multivariable functions w.r.t xj independent variables

 null matrix of order 3*3


Matrix([
[0, 0, 0],
[0, 0, 0],
[0, 0, 0]])

In [6]:
print('Jacobian of fi multivariable functions w.r.t xj independent variables')
from sympy import*
a=symbols('x,y')
f=sympify(['exp(x)*cos(y)','exp(x)*sin(y)'])
nm=zeros(len(f),len(a))
print('\n nullmatrix of order 3*3')
display(nm)
for i,fi in enumerate(f):
 for j,aj in enumerate(a):
   nm[i,j]=diff(fi,aj)
print('\n matrix corresponding to jacobian')
display(nm)
print('\n jacobian as fuction of x,y,z')
j=Matrix.det(nm)
display(simplify(j),j)

Jacobian of fi multivariable functions w.r.t xj independent variables

 nullmatrix of order 3*3


Matrix([
[0, 0],
[0, 0]])


 matrix corresponding to jacobian


Matrix([
[exp(x)*cos(y), -exp(x)*sin(y)],
[exp(x)*sin(y),  exp(x)*cos(y)]])


 jacobian as fuction of x,y,z


exp(2*x)

exp(2*x)*sin(y)**2 + exp(2*x)*cos(y)**2

In [9]:
print('Jacobian of fi multivariable functions w.r.t xj independent variables')
from sympy import*
a=symbols('x,y,z')
x,y,z=symbols('x,y,z')
f=sympify(['x*y*z','x**2+y**2+z**2','x+y+z'])
nm=zeros(len(f),len(a))
print('\n nullmatrix of order 3*3')
display(nm)
for i,fi in enumerate(f):
 for j,aj in enumerate(a):
   nm[i,j]=diff(fi,aj)
print('\n matrix corresponding to jacobian')
display(nm)
print('\n jacobian as fuction of x,y,z')
j=Matrix.det(nm)
display(simplify(j))
print('\n jacobian at (x=1,y=2,z=3)')
jv=j.subs([(x,1),(y,2),(z,3)])
display(jv)

Jacobian of fi multivariable functions w.r.t xj independent variables

 nullmatrix of order 3*3


Matrix([
[0, 0, 0],
[0, 0, 0],
[0, 0, 0]])


 matrix corresponding to jacobian


Matrix([
[y*z, x*z, x*y],
[2*x, 2*y, 2*z],
[  1,   1,   1]])


 jacobian as fuction of x,y,z


2*x**2*y - 2*x**2*z - 2*x*y**2 + 2*x*z**2 + 2*y**2*z - 2*y*z**2


 jacobian at (x=1,y=2,z=3)


-4